
Global seed set to 1234
Traceback (most recent call last):
  File "./Example-5.py", line 39, in <module>
    data = HCEikonalPINNsData(dict_args, batch_size=int(nx*nz*ns)//200)
  File "/home/taufikmh/KAUST/fall_2022/external_repos/HCPINNsEikonal3D/src/hcpinnseikonal/distributed.py", line 561, in __init__
    X, Y, Z, SX, SY, SZ, taud, taudx, taudy, T0, px0, py0, pz0, index, self.sx, self.sy, self.sz, rx, ry, rz, self.velmodel = setup_medium(args)
  File "/home/taufikmh/KAUST/fall_2022/external_repos/HCPINNsEikonal3D/src/hcpinnseikonal/distributed.py", line 298, in setup_medium
    T_data3d = numerical_traveltime3d(vel3d, len(x), len(y), len(z), len(id_sou),
  File "/home/taufikmh/KAUST/fall_2022/external_repos/HCPINNsEikonal3D/src/hcpinnseikonal/train3d.py", line 33, in numerical_traveltime3d
    solver.velocity.values = vel.reshape(nz, ny, nx)
ValueError: cannot reshape array of size 1500000 into shape (200,134,134)